//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class documentos_profe
    {
        public int id { get; set; }
        public int id_curso { get; set; }
        public int id_profesor { get; set; }
        public string url { get; set; }
        [Required(ErrorMessage = "Ingresa una titulo para el documento")]
        public string titulo { get; set; }
        public Nullable<bool> visibilidad { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
